In [1]:
import numpy as np
import pandas as pd

from src.data_utils import fetch_hourly_weather_range

# Fetching 2000-2003

In [2]:
# Variables to fetch
HOURLY_VARS = [
    "temperature_2m",
    "relative_humidity_2m",
    "dew_point_2m",
    "apparent_temperature",
    "precipitation",
    "pressure_msl",
    "wind_speed_10m",
    "wind_direction_10m",
    "cloud_cover",
    "shortwave_radiation",
    "wet_bulb_temperature_2m",
]

In [3]:
df_00_03 = fetch_hourly_weather_range(
    start_year=2000,
    end_year=2003,
    hourly_vars=HOURLY_VARS,
    save_path=None
)

Fetching 2000-01-01 → 2000-06-30 ...
Success: 2000-01-01 → 2000-06-30 (4368 rows)
Fetching 2000-07-01 → 2000-12-31 ...
Success: 2000-07-01 → 2000-12-31 (4416 rows)
Fetching 2001-01-01 → 2001-06-30 ...
Success: 2001-01-01 → 2001-06-30 (4344 rows)
Fetching 2001-07-01 → 2001-12-31 ...
Success: 2001-07-01 → 2001-12-31 (4416 rows)
Fetching 2002-01-01 → 2002-06-30 ...
Success: 2002-01-01 → 2002-06-30 (4344 rows)
Fetching 2002-07-01 → 2002-12-31 ...
Success: 2002-07-01 → 2002-12-31 (4416 rows)
Fetching 2003-01-01 → 2003-06-30 ...
Success: 2003-01-01 → 2003-06-30 (4344 rows)
Fetching 2003-07-01 → 2003-12-31 ...
Success: 2003-07-01 → 2003-12-31 (4416 rows)

In [5]:
df_00_03.tail()

,temperature_2m,relative_humidity_2m,dew_point_2m,apparent_temperature,precipitation,pressure_msl,wind_speed_10m,wind_direction_10m,cloud_cover,shortwave_radiation,wet_bulb_temperature_2m
datetime,,,,,,,,,,,
2003-12-31 08:30:00,26.139999,39.750595,11.390000,23.601231,0.0,1012.299988,20.316889,209.744781,31.0,226.0,17.267332
2003-12-31 09:30:00,24.439999,45.607864,11.940001,22.191002,0.0,1012.900024,19.523155,202.782440,6.0,51.0,16.835276
2003-12-31 10:30:00,22.740000,51.028831,12.090000,20.728914,0.0,1013.200012,18.228943,189.090195,0.0,0.0,16.204350
2003-12-31 11:30:00,21.289999,55.379993,11.990001,19.381048,0.0,1013.500000,17.313717,176.423737,0.0,0.0,15.547918
2003-12-31 12:30:00,20.139999,58.859032,11.840000,18.493071,0.0,1013.799988,15.192682,166.293015,0.0,0.0,14.987936

# 00-03 Modifications

In [14]:
adelaide_04_24_df = pd.read_csv(
    "data/processed/adelaide_hourly_weather_cleaned.csv",
    parse_dates=["datetime_utc"],
    index_col="datetime_utc"
)
adelaide_04_24_df["datetime_local"] = adelaide_04_24_df.index.tz_convert("Australia/Adelaide")

In [15]:
adelaide_04_24_df.head()

,temperature_2m,relative_humidity_2m,dew_point_2m,apparent_temperature,precipitation,pressure_msl,wind_speed_10m,wind_direction_10m,cloud_cover,shortwave_radiation,wet_bulb_temperature_2m,datetime_local,date_local,hour_local,month_local,wind_direction_compass,wind_unit_x,wind_unit_y
datetime_utc,,,,,,,,,,,,,,,,,,
2003-12-31 13:30:00+00:00,19.189999,62.846900,11.940001,17.814700,0.0,1013.6,13.551500,163.00910,0.0,0.0,14.638624,2004-01-01 00:00:00+10:30,2004-01-01,0,1,S,-0.956351,0.292220
2003-12-31 14:30:00+00:00,18.390000,67.164460,12.190001,17.394241,0.0,1013.3,11.503113,159.86362,0.0,0.0,14.437140,2004-01-01 01:00:00+10:30,2004-01-01,1,1,S,-0.938876,0.344256
2003-12-31 15:30:00+00:00,17.740000,71.356514,12.490001,17.008575,0.0,1012.8,10.365251,159.67677,0.0,0.0,14.335859,2004-01-01 02:00:00+10:30,2004-01-01,2,1,S,-0.937748,0.347316
2003-12-31 16:30:00+00:00,17.189999,75.343920,12.790000,16.558638,0.0,1012.8,10.365251,159.67677,0.0,0.0,14.287519,2004-01-01 03:00:00+10:30,2004-01-01,3,1,S,-0.937748,0.347316
2003-12-31 17:30:00+00:00,16.640000,79.822290,13.140000,16.225534,0.0,1013.1,9.693296,158.19853,0.0,0.0,14.282982,2004-01-01 04:00:00+10:30,2004-01-01,4,1,S,-0.928476,0.371392

In [9]:
df_00_03.index.rename('datetime_utc', inplace=True)

In [ ]:
# Making index timezone aware
df_00_03.index = df_00_03.index.tz_localize("UTC")
df_00_03.index.tz

datetime.timezone.utc

In [ ]:
# Util date columns
df_00_03["datetime_local"] = df_00_03.index.tz_convert("Australia/Adelaide")
df_00_03["date_local"] = df_00_03["datetime_local"].dt.date
df_00_03["hour_local"] = df_00_03["datetime_local"].dt.hour
df_00_03["month_local"] = df_00_03["datetime_local"].dt.month
df_00_03[['datetime_local', 'date_local', 'hour_local', 'month_local']].head()

,datetime_local,date_local,hour_local,month_local
datetime_utc,,,,
1999-12-31 13:30:00+00:00,2000-01-01 00:00:00+10:30,2000-01-01,0,1
1999-12-31 14:30:00+00:00,2000-01-01 01:00:00+10:30,2000-01-01,1,1
1999-12-31 15:30:00+00:00,2000-01-01 02:00:00+10:30,2000-01-01,2,1
1999-12-31 16:30:00+00:00,2000-01-01 03:00:00+10:30,2000-01-01,3,1
1999-12-31 17:30:00+00:00,2000-01-01 04:00:00+10:30,2000-01-01,4,1

In [ ]:
# Wind direction columns
from src.general_utils import wind_to_compass8

df_00_03['wind_direction_compass'] = wind_to_compass8(df_00_03['wind_direction_10m'])
df_00_03['wind_unit_x'] = np.cos(np.deg2rad(df_00_03['wind_direction_10m'])) 
df_00_03['wind_unit_y'] = np.sin(np.deg2rad(df_00_03['wind_direction_10m']))
df_00_03[['wind_direction_10m', 'wind_direction_compass', 'wind_unit_x', 'wind_unit_y']].head()

,wind_direction_10m,wind_direction_compass,wind_unit_x,wind_unit_y
datetime_utc,,,,
1999-12-31 13:30:00+00:00,149.452499,SE,-0.861208,0.508253
1999-12-31 14:30:00+00:00,144.360107,SE,-0.812695,0.582689
1999-12-31 15:30:00+00:00,139.707932,SE,-0.762758,0.646684
1999-12-31 16:30:00+00:00,136.468735,SE,-0.724999,0.688750
1999-12-31 17:30:00+00:00,135.763809,SE,-0.716470,0.697618

# Merging 00-03 with 04-24

In [19]:
df_00_03.index[-1], adelaide_04_24_df.index[0]

(Timestamp('2003-12-31 12:30:00+0000', tz='UTC'),
 Timestamp('2003-12-31 13:30:00+0000', tz='UTC'))

In [20]:
adelaide_hourly_clean = pd.concat([df_00_03, adelaide_04_24_df], axis=0)
adelaide_hourly_clean.head()

,temperature_2m,relative_humidity_2m,dew_point_2m,apparent_temperature,precipitation,pressure_msl,wind_speed_10m,wind_direction_10m,cloud_cover,shortwave_radiation,wet_bulb_temperature_2m,datetime_local,date_local,hour_local,month_local,wind_direction_compass,wind_unit_x,wind_unit_y
datetime_utc,,,,,,,,,,,,,,,,,,
1999-12-31 13:30:00+00:00,12.990001,70.450943,7.74,8.684013,0.0,1019.000000,25.499081,149.452499,2.0,0.0,9.796810,2000-01-01 00:00:00+10:30,2000-01-01,0,1,SE,-0.861208,0.508253
1999-12-31 14:30:00+00:00,12.790000,70.172134,7.49,8.716958,0.0,1018.700012,23.477409,144.360107,2.0,0.0,9.581293,2000-01-01 01:00:00+10:30,2000-01-01,1,1,SE,-0.812695,0.582689
1999-12-31 15:30:00+00:00,12.540000,69.644913,7.14,8.639514,0.0,1018.500000,21.710716,139.707932,3.0,0.0,9.293997,2000-01-01 02:00:00+10:30,2000-01-01,2,1,SE,-0.762758,0.646684
1999-12-31 16:30:00+00:00,12.190001,69.814163,6.84,8.487599,0.0,1018.200012,19.862083,136.468735,11.0,0.0,8.985559,2000-01-01 03:00:00+10:30,2000-01-01,3,1,SE,-0.724999,0.688750
1999-12-31 17:30:00+00:00,11.840000,70.709984,6.69,8.214409,0.0,1018.200012,19.093580,135.763809,6.0,0.0,8.750040,2000-01-01 04:00:00+10:30,2000-01-01,4,1,SE,-0.716470,0.697618

In [21]:
adelaide_hourly_clean.tail()

,temperature_2m,relative_humidity_2m,dew_point_2m,apparent_temperature,precipitation,pressure_msl,wind_speed_10m,wind_direction_10m,cloud_cover,shortwave_radiation,wet_bulb_temperature_2m,datetime_local,date_local,hour_local,month_local,wind_direction_compass,wind_unit_x,wind_unit_y
datetime_utc,,,,,,,,,,,,,,,,,,
2024-12-31 08:30:00+00:00,24.287500,45.117104,11.6375,22.877293,0.0,1015.5,13.115319,226.66829,0.0,249.0,16.629898,2024-12-31 19:00:00+10:30,2024-12-31,19,12,SW,-0.686221,-0.727393
2024-12-31 09:30:00+00:00,23.687500,54.195713,13.8875,22.761864,0.0,1015.6,14.967083,183.44731,0.0,59.0,17.489100,2024-12-31 20:00:00+10:30,2024-12-31,20,12,S,-0.998191,-0.060131
2024-12-31 10:30:00+00:00,20.937500,62.016243,13.3875,19.678705,0.0,1016.1,16.055353,160.34608,0.0,0.0,16.117443,2024-12-31 21:00:00+10:30,2024-12-31,21,12,S,-0.941741,0.336338
2024-12-31 11:30:00+00:00,19.187500,67.770226,13.0875,18.090760,0.0,1016.5,14.241630,159.27437,2.0,0.0,15.247961,2024-12-31 22:00:00+10:30,2024-12-31,22,12,S,-0.935286,0.353893
2024-12-31 12:30:00+00:00,18.137499,70.041145,12.5875,17.065443,0.0,1016.6,12.921192,161.31256,0.0,0.0,14.550007,2024-12-31 23:00:00+10:30,2024-12-31,23,12,S,-0.947281,0.320405

# Adding Heatwave Columns to 00-24

Adding `'DMT', 'tmin', 'tmax', 'EHI_sig', 'EHI_accl', 'EHF', 'EHF_sev', 'severity'` columns from *"temperature_1958_2024.csv"* to original *2000-2024* clean data.

In [22]:
temp_df = pd.read_csv('data/processed/temperature_1958_2024.csv',
    parse_dates=["datetime_utc"],
    index_col="datetime_utc"
)
temp_df["datetime_local"] = temp_df.index.tz_convert("Australia/Adelaide")
temp_df.head()

,temperature_2m,datetime_local,DMT,tmin,tmax,EHI_sig,EHI_accl,EHF,EHF_sev,severity
datetime_utc,,,,,,,,,,
1957-12-31 14:30:00+00:00,14.240001,1958-01-01 00:00:00+09:30,17.289999,12.79,21.789999,-8.070417,NaN,NaN,NaN,NaN
1957-12-31 15:30:00+00:00,14.390000,1958-01-01 01:00:00+09:30,17.289999,12.79,21.789999,-8.070417,NaN,NaN,NaN,NaN
1957-12-31 16:30:00+00:00,14.440001,1958-01-01 02:00:00+09:30,17.289999,12.79,21.789999,-8.070417,NaN,NaN,NaN,NaN
1957-12-31 17:30:00+00:00,14.490001,1958-01-01 03:00:00+09:30,17.289999,12.79,21.789999,-8.070417,NaN,NaN,NaN,NaN
1957-12-31 18:30:00+00:00,13.890000,1958-01-01 04:00:00+09:30,17.289999,12.79,21.789999,-8.070417,NaN,NaN,NaN,NaN

In [26]:
adelaide_hourly_clean = adelaide_hourly_clean.join(temp_df.drop(columns=['temperature_2m', 'datetime_local']), how='left')
adelaide_hourly_clean.head()

,temperature_2m,relative_humidity_2m,dew_point_2m,apparent_temperature,precipitation,pressure_msl,wind_speed_10m,wind_direction_10m,cloud_cover,shortwave_radiation,...,wind_unit_x,wind_unit_y,DMT,tmin,tmax,EHI_sig,EHI_accl,EHF,EHF_sev,severity
datetime_utc,,,,,,,,,,,,,,,,,,,,,
1999-12-31 13:30:00+00:00,12.990001,70.450943,7.74,8.684013,0.0,1019.000000,25.499081,149.452499,2.0,0.0,...,-0.861208,0.508253,16.015,12.29,19.74,-8.062083,-1.385,-8.062083,0.0,No-heatwave
1999-12-31 14:30:00+00:00,12.790000,70.172134,7.49,8.716958,0.0,1018.700012,23.477409,144.360107,2.0,0.0,...,-0.812695,0.582689,16.015,12.29,19.74,-8.062083,-1.385,-8.062083,0.0,No-heatwave
1999-12-31 15:30:00+00:00,12.540000,69.644913,7.14,8.639514,0.0,1018.500000,21.710716,139.707932,3.0,0.0,...,-0.762758,0.646684,16.015,12.29,19.74,-8.062083,-1.385,-8.062083,0.0,No-heatwave
1999-12-31 16:30:00+00:00,12.190001,69.814163,6.84,8.487599,0.0,1018.200012,19.862083,136.468735,11.0,0.0,...,-0.724999,0.688750,16.015,12.29,19.74,-8.062083,-1.385,-8.062083,0.0,No-heatwave
1999-12-31 17:30:00+00:00,11.840000,70.709984,6.69,8.214409,0.0,1018.200012,19.093580,135.763809,6.0,0.0,...,-0.716470,0.697618,16.015,12.29,19.74,-8.062083,-1.385,-8.062083,0.0,No-heatwave

In [27]:
# Overwriting on old clean ready data since this is the current last clean version
adelaide_hourly_clean.to_csv('data/processed/adelaide_hourly_weather_cleaned.csv', index=True, index_label="datetime_utc")

In [28]:
adelaide_hourly_clean

,temperature_2m,relative_humidity_2m,dew_point_2m,apparent_temperature,precipitation,pressure_msl,wind_speed_10m,wind_direction_10m,cloud_cover,shortwave_radiation,...,wind_unit_x,wind_unit_y,DMT,tmin,tmax,EHI_sig,EHI_accl,EHF,EHF_sev,severity
datetime_utc,,,,,,,,,,,,,,,,,,,,,
1999-12-31 13:30:00+00:00,12.990001,70.450943,7.7400,8.684013,0.0,1019.000000,25.499081,149.452499,2.0,0.0,...,-0.861208,0.508253,16.0150,12.290000,19.7400,-8.062083,-1.385000,-8.062083,0.0,No-heatwave
1999-12-31 14:30:00+00:00,12.790000,70.172134,7.4900,8.716958,0.0,1018.700012,23.477409,144.360107,2.0,0.0,...,-0.812695,0.582689,16.0150,12.290000,19.7400,-8.062083,-1.385000,-8.062083,0.0,No-heatwave
1999-12-31 15:30:00+00:00,12.540000,69.644913,7.1400,8.639514,0.0,1018.500000,21.710716,139.707932,3.0,0.0,...,-0.762758,0.646684,16.0150,12.290000,19.7400,-8.062083,-1.385000,-8.062083,0.0,No-heatwave
1999-12-31 16:30:00+00:00,12.190001,69.814163,6.8400,8.487599,0.0,1018.200012,19.862083,136.468735,11.0,0.0,...,-0.724999,0.688750,16.0150,12.290000,19.7400,-8.062083,-1.385000,-8.062083,0.0,No-heatwave
1999-12-31 17:30:00+00:00,11.840000,70.709984,6.6900,8.214409,0.0,1018.200012,19.093580,135.763809,6.0,0.0,...,-0.716470,0.697618,16.0150,12.290000,19.7400,-8.062083,-1.385000,-8.062083,0.0,No-heatwave
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-12-31 08:30:00+00:00,24.287500,45.117104,11.6375,22.877293,0.0,1015.500000,13.115319,226.668290,0.0,249.0,...,-0.686221,-0.727393,21.1125,15.537499,26.6875,-6.031250,-1.406667,-6.031250,0.0,No-heatwave
2024-12-31 09:30:00+00:00,23.687500,54.195713,13.8875,22.761864,0.0,1015.600000,14.967083,183.447310,0.0,59.0,...,-0.998191,-0.060131,21.1125,15.537499,26.6875,-6.031250,-1.406667,-6.031250,0.0,No-heatwave
2024-12-31 10:30:00+00:00,20.937500,62.016243,13.3875,19.678705,0.0,1016.100000,16.055353,160.346080,0.0,0.0,...,-0.941741,0.336338,21.1125,15.537499,26.6875,-6.031250,-1.406667,-6.031250,0.0,No-heatwave
2024-12-31 11:30:00+00:00,19.187500,67.770226,13.0875,18.090760,0.0,1016.500000,14.241630,159.274370,2.0,0.0,...,-0.935286,0.353893,21.1125,15.537499,26.6875,-6.031250,-1.406667,-6.031250,0.0,No-heatwave
2024-12-31 12:30:00+00:00,18.137499,70.041145,12.5875,17.065443,0.0,1016.600000,12.921192,161.312560,0.0,0.0,...,-0.947281,0.320405,21.1125,15.537499,26.6875,-6.031250,-1.406667,-6.031250,0.0,No-heatwave

# El Nino Southern Oscilation (ENSO) Index  Preprocesssing

In [42]:
# Load the text file
# We assign column names since your snippet doesn't have a header
soi = pd.read_csv('data/raw/soi_monthly.txt', names=['Date', 'Value'])

# turn '187601' into an actual datetime (1876-01-01)
soi['Date'] = pd.to_datetime(soi['Date'], format='%Y%m')
soi.head()

        Date  Value
0 1876-01-01   11.3
1 1876-02-01   11.0
2 1876-03-01    0.2
3 1876-04-01    9.4
4 1876-05-01    6.8

In [43]:
soi_yearly = soi.groupby(soi['Date'].dt.year).mean()
soi_yearly.head()

                    Date      Value
Date
1876 1876-06-16 08:00:00   4.950000
1877 1877-06-16 12:00:00 -10.041667
1878 1878-06-16 12:00:00   2.950000
1879 1879-06-16 12:00:00  12.850000
1880 1880-06-16 08:00:00   7.800000

In [44]:
soi_yearly['Date'] = soi_yearly.index
soi_yearly.rename(columns={'Date': 'year', 'Value': 'SOI'}, inplace=True)
soi_yearly.head()

      year        SOI
Date
1876  1876   4.950000
1877  1877 -10.041667
1878  1878   2.950000
1879  1879  12.850000
1880  1880   7.800000

In [45]:
soi_yearly.to_csv('data/processed/soi_yearly.csv', index=False)